### PR TITLE
Remove check if ssl files exist

### PR DESCRIPTION
**Pull request by DewGew**

### CODE REVIEW

**Comment by Xenomes** [comment]
Hi, thanks for the update.
I've updated the Git. However, when I start it, I can't log in anymore.
The CLI log only reports two lines:
```
2023-11-18 21:56:23 Smarthome server has started.
2023-11-18 21:56:23 Running with ssl
```
To regain access, I updated the db usessl to 0.

**Comment by DewGew** [comment]
Did you try with https instead of http?

**Comment by Xenomes** [comment]
Yes i did, even with and without / login. Tomorrow i will test it outside the docker container.

**Comment by Xenomes** [comment]
Outside of the Docker container is not working for me. I will try a clean virtual install later today.

P.S. There are some typos in the wiki installation guide.
https://raw.githubusercontent.com/DewGew/DZGA-Flask/development/scripts/install.sh
source DZGA-Flask/env/bin/activate
At the uninstall Flask to flask

**Comment by Xenomes** [comment]
On a clean install, running in the Python venv, SSL works. Running it in Docker (Dockerfile) results in an error:
```
Traceback (most recent call last):
  File "/smarthome.py", line 428, in <module>
    app.run('0.0.0.0', port=8181, debug=True, ssl_context=context)
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 889, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/usr/local/lib/python3.12/site-packages/werkzeug/serving.py", line 1075, in run_simple
    srv = make_server(
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/werkzeug/serving.py", line 915, in make_server
    return ThreadedWSGIServer(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/werkzeug/serving.py", line 790, in __init__
    ssl_context = load_ssl_context(*ssl_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/werkzeug/serving.py", line 633, in load_ssl_context
    ctx.load_cert_chain(cert_file, pkey_file)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by DewGew** [comment]
Ok im not using docker. I cant help you there. I hope someone else knows.

**Comment by Xenomes** [comment]
Okay, i was able to run/start it as a services on my live system.

**Pull request merged**
